export const sampleWholesaleDeals = [
  {
    id: 1,
    submittedBy: "demo-wholesaler-001",
    propertyAddress: "4521 W McDowell Rd, Phoenix, AZ 85035",
    city: "Phoenix",
    state: "AZ",
    zipCode: "85035",
    propertyType: "Single Family",
    arv: 385000,
    askingPrice: 225000,
    repairEstimate: 75000,
    assignmentFee: 15000,
    occupancyStatus: "Vacant",
    closeTimeline: "21 days",
    dealNotes: "Motivated seller, recently inherited property. 3BR/2BA, 1,450 sqft. Needs full cosmetic rehab.",
    status: "Listed",
    isPublic: true,
    photos: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800"],
  },
  {
    id: 2,
    submittedBy: "demo-wholesaler-001",
    propertyAddress: "7832 N 19th Ave, Phoenix, AZ 85021",
    city: "Phoenix",
    state: "AZ",
    zipCode: "85021",
    propertyType: "Single Family",
    arv: 425000,
    askingPrice: 265000,
    repairEstimate: 60000,
    assignmentFee: 18000,
    occupancyStatus: "Owner Occupied",
    closeTimeline: "30 days",
    dealNotes: "Estate sale, family needs quick close. 4BR/2BA, 1,800 sqft. Pool home! Needs cosmetic updates.",
    status: "Listed",
    isPublic: true,
    photos: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800"],
  },
  {
    id: 3,
    submittedBy: "demo-wholesaler-002",
    propertyAddress: "2156 E University Dr, Mesa, AZ 85213",
    city: "Mesa",
    state: "AZ",
    zipCode: "85213",
    propertyType: "Single Family",
    arv: 345000,
    askingPrice: 195000,
    repairEstimate: 85000,
    assignmentFee: 12000,
    occupancyStatus: "Vacant",
    closeTimeline: "14 days",
    dealNotes: "Fire damaged property - insurance settled. 3BR/2BA. Needs major renovation.",
    status: "Listed",
    isPublic: true,
    photos: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"],
  },
  {
    id: 4,
    submittedBy: "demo-wholesaler-001",
    propertyAddress: "9012 S 48th St, Phoenix, AZ 85044",
    city: "Phoenix",
    state: "AZ",
    zipCode: "85044",
    propertyType: "Single Family",
    arv: 520000,
    askingPrice: 350000,
    repairEstimate: 45000,
    assignmentFee: 22000,
    occupancyStatus: "Tenant Occupied",
    closeTimeline: "45 days",
    dealNotes: "Ahwatukee location! Tenant in place paying $2,200/month. Perfect for buy-and-hold investor.",
    status: "Under Review",
    isPublic: true,
    photos: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"],
  },
  {
    id: 5,
    submittedBy: "demo-wholesaler-002",
    propertyAddress: "3345 W Baseline Rd, Laveen, AZ 85339",
    city: "Laveen",
    state: "AZ",
    zipCode: "85339",
    propertyType: "Single Family",
    arv: 295000,
    askingPrice: 175000,
    repairEstimate: 55000,
    assignmentFee: 10000,
    occupancyStatus: "Vacant",
    closeTimeline: "21 days",
    dealNotes: "Bank REO property. 3BR/2BA, 1,200 sqft. Needs full rehab. Good starter flip.",
    status: "Listed",
    isPublic: true,
    photos: ["https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800"],
  },
];

export const sampleCapitalProjects = [
  {
    id: 1,
    userId: "demo-dreamscaper-001",
    title: "Scottsdale Fix & Flip - Luxury Single Family",
    description: "Acquiring a distressed luxury property in North Scottsdale. Target ARV of $1.2M after full renovation including pool, kitchen, and landscaping upgrades.",
    location: "Scottsdale, AZ",
    propertyType: "Single Family",
    fundingStructure: "EQUITY",
    fundingGoal: 250000,
    amountRaised: 175000,
    minInvestment: 25000,
    projectedReturn: "18-22% IRR",
    holdPeriod: "8-12 months",
    photos: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800"],
    status: "OPEN_FOR_INVESTMENT",
    isPublic: true,
  },
  {
    id: 2,
    userId: "demo-dreamscaper-001",
    title: "Mesa Multi-Family Renovation",
    description: "8-unit apartment complex needing cosmetic updates. Strong rental demand in the area with 95% occupancy in surrounding properties.",
    location: "Mesa, AZ",
    propertyType: "Multi-Family",
    fundingStructure: "DEBT",
    fundingGoal: 85000,
    amountRaised: 85000,
    minInvestment: 10000,
    projectedReturn: "12% annual interest",
    holdPeriod: "12 months",
    photos: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800"],
    status: "FUNDED",
    isPublic: true,
  },
  {
    id: 3,
    userId: "demo-dreamscaper-002",
    title: "Gilbert Rental Portfolio Acquisition",
    description: "Acquiring a 4-property rental portfolio in Gilbert. All properties leased with strong NOI. Seeking equity partners.",
    location: "Gilbert, AZ",
    propertyType: "Multi-Family",
    fundingStructure: "EQUITY",
    fundingGoal: 280000,
    amountRaised: 140000,
    minInvestment: 50000,
    projectedReturn: "15-18% CoC + Appreciation",
    holdPeriod: "5 years",
    photos: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800"],
    status: "OPEN_FOR_INVESTMENT",
    isPublic: true,
  },
  {
    id: 4,
    userId: "demo-dreamscaper-001",
    title: "Tempe Townhome Development",
    description: "Ground-up construction of 6 townhomes near ASU campus. Pre-sold units with strong buyer demand. Hybrid funding structure.",
    location: "Tempe, AZ",
    propertyType: "Townhome",
    fundingStructure: "HYBRID",
    fundingGoal: 450000,
    amountRaised: 125000,
    minInvestment: 25000,
    projectedReturn: "25-35%",
    holdPeriod: "18-24 months",
    photos: ["https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800"],
    status: "OPEN_FOR_INVESTMENT",
    isPublic: true,
  },
];

export const sampleInvestorStats = {
  totalInvested: 175000,
  activeInvestments: 3,
  totalReturns: 28500,
  averageROI: 16.3,
  pendingOffers: 2,
  watchlistCount: 8,
};

export const sampleWholesalerStats = {
  activeDeals: 4,
  pendingReview: 1,
  closedDeals: 12,
  totalEarnings: 185000,
  averageAssignmentFee: 15400,
  jvRequestsReceived: 3,
};

export const sampleDreamscaperStats = {
  activeProjects: 3,
  totalRaised: 400000,
  investorCount: 12,
  pendingOffers: 4,
  completedProjects: 5,
  averageReturn: 21.5,
};

export const sampleBuyerStats = {
  savedProperties: 8,
  activeOffers: 2,
  viewedProperties: 24,
  acceptedOffers: 1,
  closedDeals: 3,
};

export const sampleRetailListings = [
  {
    id: 1,
    title: "Renovated Craftsman in Historic District",
    address: "1234 N 7th Ave",
    city: "Phoenix",
    state: "AZ",
    zipCode: "85007",
    propertyType: "Single Family",
    price: 425000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1650,
    description: "Beautifully renovated Craftsman bungalow in the historic Coronado neighborhood.",
    photos: ["https://images.unsplash.com/photo-1600573472556-e636c2acda88?w=800"],
    status: "active",
  },
  {
    id: 2,
    title: "Modern Desert Contemporary",
    address: "8765 E Pinnacle Peak Rd",
    city: "Scottsdale",
    state: "AZ",
    zipCode: "85255",
    propertyType: "Single Family",
    price: 875000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3200,
    description: "Stunning modern desert home with panoramic mountain views.",
    photos: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"],
    status: "active",
  },
  {
    id: 3,
    title: "Cozy Starter Home",
    address: "5432 W Glendale Ave",
    city: "Glendale",
    state: "AZ",
    zipCode: "85301",
    propertyType: "Single Family",
    price: 285000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1200,
    description: "Perfect starter home in a quiet neighborhood with great schools.",
    photos: ["https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800"],
    status: "active",
  },
];

export const sampleCommittedInvestments = [
  {
    id: 1,
    projectId: 1,
    investorId: "demo-investor-001",
    committedAmount: 50000,
    status: "committed",
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
  },
  {
    id: 2,
    projectId: 2,
    investorId: "demo-investor-001",
    committedAmount: 25000,
    status: "funded",
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
  },
];

export const samplePendingOffers = [
  {
    id: 1,
    projectId: 3,
    investorId: "demo-investor-002",
    offeredAmount: 75000,
    status: "pending",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
];
