import {beforeAll,afterAll,describe,it,expect} from 'vitest';import {sql} from 'drizzle-orm';import {readFile} from 'node:fs/promises';
import {createWebsiteDb,type WebsiteDb} from '../db';import {recordWebsiteInquiry} from '../intake';import {listWebsiteDeliveryJobs} from '../delivery-admin';import {assertWebsiteTestTarget} from '../../../scripts/website-db-test-target.mjs';
const org='a7000000-0000-4000-8000-000000000001',other='a7000000-0000-4000-8000-000000000002';
describe.skipIf(process.env.WEBSITE_DB_TESTS!=='1')('delivery admin organization boundary',()=>{
 let db:WebsiteDb,close:()=>Promise<void>,old:string|undefined;
 beforeAll(async()=>{({db,close}=createWebsiteDb(assertWebsiteTestTarget(process.env.WEBSITE_TEST_DATABASE_URL)));await db.execute(sql.raw(await readFile(new URL('../../../migrations/website/0001_website_foundation.sql',import.meta.url),'utf8')));old=process.env.WEBSITE_ORG_ID;process.env.WEBSITE_ORG_ID=org;await recordWebsiteInquiry({kind:'lead',idempotencyKey:'a7000000-0000-4000-8000-000000000003',authSubject:null,payload:{leadType:'contact',source:'test',firstName:'Synthetic',email:'synthetic@example.test'}},db);});
 afterAll(async()=>{for(const t of ['notification_outbox','delivery_jobs','intake_requests','admin_audit_log','leads'])await db.execute(sql`delete from ${sql.identifier('website')}.${sql.identifier(t)} where org_id=${org}::uuid`);await close();if(old===undefined)delete process.env.WEBSITE_ORG_ID;else process.env.WEBSITE_ORG_ID=old;});
 it('lists current-contract deliveries for only the authorized organization',async()=>{expect(await listWebsiteDeliveryJobs(db,other)).toEqual([]);const own=await listWebsiteDeliveryJobs(db,org);expect(own).toHaveLength(1);expect(own[0].status).toBe('pending');expect(own[0].payload).toEqual(expect.objectContaining({contractVersion:1}));});
 it('retains quarantine visibility and never labels it delivered',async()=>{await db.execute(sql`update website.delivery_jobs set status='quarantined',last_error='invalid_receipt' where org_id=${org}::uuid`);const rows=await listWebsiteDeliveryJobs(db,org,'quarantined');expect(rows).toHaveLength(1);expect(rows[0].deliveredAt).toBeNull();expect(rows[0].lastError).toBe('invalid_receipt');});
});
