import { describe, it, expect } from 'vitest';
import { buyerCriteriaV1Schema, buyerCriteriaLeadSubmissionV1Schema, buildBuyerCriteriaLeadSubmission, createEmptyBuyerCriteriaDraft } from '../../shared/buyer-criteria';
const criteria = () => ({version:1,geography:[{country:'US',stateCode:'CA',kind:'city',name:'Oakland'}],assetTypes:['single_family'],priceRange:{currency:'USD',min:null,max:null,basis:'undecided'},strategies:['undecided'],rehabExclusions:[],occupancyExclusions:[],timing:{purchaseHorizon:'exploring',closingDays:null},purchaser:{entityType:'undecided',entityName:null,role:'principal'},funding:{selfReported:true,status:'undecided'}});
describe('strict reviewed buyer criteria transport',()=>{
 it('preserves unknown amounts and self-reported capacity without fabricating defaults',()=>{expect(buyerCriteriaV1Schema.parse(criteria())).toEqual(criteria());const d=createEmptyBuyerCriteriaDraft();expect(d.consentContact).toBe(false);expect(d.emailOptIn).toBe(false);expect(()=>buildBuyerCriteriaLeadSubmission(d)).toThrow();});
 it.each([
 ['version',{version:2}],['unknown key',{verified:true}],['empty geography',{geography:[]}],['duplicate geography',{geography:[{country:'US',stateCode:'CA',kind:'city',name:'Oakland'},{country:'US',stateCode:'CA',kind:'city',name:' oakland '}]}],['invalid state',{geography:[{country:'US',stateCode:'XX',kind:'state'}]}],['ZIP',{geography:[{country:'US',stateCode:'CA',kind:'zip',postalCode:'1234'}]}],['empty assets',{assetTypes:[]}],['duplicate assets',{assetTypes:['land','land']}],['mixed undecided',{strategies:['undecided','development']}],['number coercion',{priceRange:{currency:'USD',min:null,max:'300000',basis:'purchase_price'}}],['fractional dollars',{priceRange:{currency:'USD',min:null,max:1.1,basis:'all_in'}}],['max boundary',{priceRange:{currency:'USD',min:null,max:1000000000001,basis:'all_in'}}],['negative',{priceRange:{currency:'USD',min:-1,max:100,basis:'all_in'}}],['reverse range',{priceRange:{currency:'USD',min:101,max:100,basis:'purchase_price'}}],['missing max',{priceRange:{currency:'USD',min:null,max:null,basis:'purchase_price'}}],['undecided numbers',{priceRange:{currency:'USD',min:0,max:null,basis:'undecided'}}],['unknown timing',{timing:{purchaseHorizon:'exploring',closingDays:0}}],['long timing',{timing:{purchaseHorizon:'exploring',closingDays:366}}],['role not chosen',{purchaser:{entityType:'undecided',entityName:null,role:''}}],['verified capacity',{funding:{selfReported:false,status:'cash'}}],
 ])('rejects %s',(_label,patch)=>expect(buyerCriteriaV1Schema.safeParse({...criteria(),...patch}).success).toBe(false));
 it('trims geography and accepts integer boundaries and unformed entities',()=>{expect(buyerCriteriaV1Schema.parse({...criteria(),geography:[{country:'US',stateCode:'CA',kind:'county',name:' Alameda '}],priceRange:{currency:'USD',min:0,max:1000000000000,basis:'purchase_price'},purchaser:{entityType:'entity',entityName:null,role:'entity_representative'}}).geography[0]).toMatchObject({name:'Alameda'});});
 it('builds a deterministic independent consent payload and retains referral attribution',()=>{const d={...createEmptyBuyerCriteriaDraft(),firstName:' Ada ',email:'ada@example.test',criteria:criteria(),consentContact:true,emailOptIn:false,referredBy:' Apollo '};const p=buildBuyerCriteriaLeadSubmission(d as any);expect(p).toMatchObject({leadType:'submit',source:'form',firstName:'Ada',referredBy:'Apollo',leadData:{lane:'buyer',intent:'buyer',role:'Buyer',contextKind:'context',context:'Oakland, CA',buyerAlertConsent:{version:1,emailOptIn:false,copyVersion:'buyer-alerts-v1'}}});expect(p.leadData).not.toHaveProperty('capturedAt');expect(JSON.parse(JSON.stringify(p))).toEqual(p);});
 it('rejects criteria on wrong transport or representation intent',()=>{const p={leadType:'submit',source:'form',firstName:'Ada',email:'ada@example.test',consentContact:true,leadData:{lane:'buyer',role:'Buyer',intent:'representation',contextKind:'context',context:'Oakland, CA',consentContact:true,buyerCriteria:criteria(),buyerAlertConsent:{version:1,emailOptIn:false,copyVersion:'buyer-alerts-v1'}}};expect(buyerCriteriaLeadSubmissionV1Schema.safeParse(p).success).toBe(false);});
});
